read:
    pattern:   /read/
    defaults:  { _controller: AcmeTestBundle:Rss:index }

setting:
    pattern:   /setting/
    defaults:  { _controller: AcmeTestBundle:Rss:setting }

actionForm:
    pattern:   /setting/
    defaults:  { _controller: AcmeTestBundle:Rss:setting }
